services:
  frontend:
    build: ./frontend
    image: if4042-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
  backend:
    build: ./backend
    image: if4042-backend:latest
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: if4042
      POSTGRES_DB: query_expansion
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: