"""init migrations

Revision ID: 1020ca46fe09
Revises: 
Create Date: 2025-05-22 17:21:52.351382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1020ca46fe09'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    docs = op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('search_result', sa.Integer(), nullable=True),
    sa.Column('is_expansion', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_pairs',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('expanded_query_id', sa.Integer(), nullable=False),
    sa.Column('terms_expanded', sa.Integer(), nullable=True),
    sa.Column('used_stemming', sa.Boolean(), nullable=True),
    sa.Column('removed_stopword', sa.Boolean(), nullable=True),
    sa.Column('scheme_used', sa.Enum('LogarithmicTF', 'BinaryTF', 'AugmentationTF', 'NaturalTF', 'IDF', 'TFxIDF', 'TFxIDFxNorm', name='queryscheme'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['expanded_query_id'], ['queries.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'expanded_query_id')
    )
    op.create_table('query_results',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'document_id')
    )
    # ### end Alembic commands ###

 


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_results')
    op.drop_table('query_pairs')
    op.drop_table('queries')
    op.drop_table('documents')
    # ### end Alembic commands ###
